-- =========================================================
-- MiEstacionamiento - Creacion de tablas en Oracle ADB
-- Ejecutar como usuario ADMIN en SQL Worksheet de Oracle Cloud
-- =========================================================

-- Tabla de usuarios de la aplicacion
CREATE TABLE APP_USERS (
    ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME           VARCHAR2(100)  NOT NULL,
    EMAIL          VARCHAR2(200)  UNIQUE NOT NULL,
    PASSWORD       VARCHAR2(200)  NOT NULL,
    USER_TYPE      VARCHAR2(10)   DEFAULT 'DRIVER' CHECK (USER_TYPE IN ('DRIVER', 'OWNER')),
    PHOTO_URL      VARCHAR2(500),
    VEHICLE_BRAND  VARCHAR2(100),
    VEHICLE_PLATE  VARCHAR2(20),
    ADDRESS        VARCHAR2(300),
    COMMUNE        VARCHAR2(100),
    REGION         VARCHAR2(100),
    CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Tabla de estacionamientos
CREATE TABLE PARKINGS (
    ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME             VARCHAR2(200) NOT NULL,
    DESCRIPTION      VARCHAR2(1000),
    ADDRESS          VARCHAR2(300),
    IMAGE_URL        VARCHAR2(500),
    LATITUDE         NUMBER(11, 7),
    LONGITUDE        NUMBER(11, 7),
    PRICE_PER_HOUR   NUMBER(10, 2) DEFAULT 0,
    AVAILABLE_SPOTS  NUMBER        DEFAULT 0,
    TOTAL_SPOTS      NUMBER        DEFAULT 0,
    RATING           NUMBER(3, 1)  DEFAULT 0,
    REVIEW_COUNT     NUMBER        DEFAULT 0,
    OWNER_ID         NUMBER REFERENCES APP_USERS(ID),
    CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Estacionamientos guardados (favoritos) por usuario
CREATE TABLE SAVED_PARKINGS (
    USER_ID     NUMBER NOT NULL REFERENCES APP_USERS(ID) ON DELETE CASCADE,
    PARKING_ID  NUMBER NOT NULL REFERENCES PARKINGS(ID) ON DELETE CASCADE,
    SAVED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY (USER_ID, PARKING_ID)
);

-- Historial de estacionamientos vistos recientemente
CREATE TABLE RECENTLY_VIEWED (
    USER_ID     NUMBER NOT NULL REFERENCES APP_USERS(ID) ON DELETE CASCADE,
    PARKING_ID  NUMBER NOT NULL REFERENCES PARKINGS(ID) ON DELETE CASCADE,
    VIEWED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY (USER_ID, PARKING_ID)
);

-- Indices para mejorar el rendimiento de las consultas frecuentes
CREATE INDEX IDX_USERS_EMAIL     ON APP_USERS(EMAIL);
CREATE INDEX IDX_PARKINGS_RATING ON PARKINGS(RATING DESC);
CREATE INDEX IDX_SAVED_USER      ON SAVED_PARKINGS(USER_ID);
CREATE INDEX IDX_RECENT_USER     ON RECENTLY_VIEWED(USER_ID, VIEWED_AT DESC);

COMMIT;
