
CREATE INDEX idx_bookings_parking ON BOOKINGS(PARKING_ID);
CREATE INDEX idx_bookings_driver  ON BOOKINGS(DRIVER_ID);
CREATE INDEX idx_bookings_created ON BOOKINGS(CREATED_AT DESC);

-- Si la tabla ya existe y solo necesitas agregar las columnas de pago:
-- ALTER TABLE BOOKINGS ADD HOURS          NUMBER(3) DEFAULT 1;
-- ALTER TABLE BOOKINGS ADD PAYMENT_METHOD VARCHAR2(30) DEFAULT 'PENDING';
-- ALTER TABLE BOOKINGS ADD PAYMENT_TOKEN  VARCHAR2(500);

-- Datos de prueba (opcional)
-- INSERT INTO BOOKINGS (PARKING_ID, DRIVER_ID, AMOUNT, STATUS, HOURS, PAYMENT_METHOD)
-- VALUES (1, 2, 2000, 'COMPLETED', 2, 'GOOGLE_PAY');
-- COMMIT;
