-- =============================================
-- Tablas para Reseñas y Chat
-- =============================================

-- Si la tabla ya existia con la columna COMMENT (palabra reservada), eliminarla primero:
-- DROP TABLE REVIEWS CASCADE CONSTRAINTS;

-- Tabla de reseñas de estacionamientos
-- NOTA: Se usa REVIEW_COMMENT en lugar de COMMENT (palabra reservada en Oracle)
CREATE TABLE REVIEWS (
    ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PARKING_ID       NUMBER NOT NULL,
    USER_ID          NUMBER NOT NULL,
    RATING           NUMBER(1) NOT NULL,
    REVIEW_COMMENT   VARCHAR2(1000),
    OWNER_RESPONSE     VARCHAR2(1000),
    OWNER_RESPONSE_AT  TIMESTAMP,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_parking FOREIGN KEY (PARKING_ID) REFERENCES PARKINGS(ID) ON DELETE CASCADE,
    CONSTRAINT fk_review_user    FOREIGN KEY (USER_ID)    REFERENCES APP_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT chk_rating        CHECK (RATING BETWEEN 1 AND 5),
    CONSTRAINT uq_review         UNIQUE (PARKING_ID, USER_ID)
);

CREATE INDEX idx_reviews_parking ON REVIEWS(PARKING_ID);
CREATE INDEX idx_reviews_user    ON REVIEWS(USER_ID);

-- Tabla de conversaciones entre conductor y propietario
CREATE TABLE CONVERSATIONS (
    ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DRIVER_ID        NUMBER NOT NULL,
    OWNER_ID         NUMBER NOT NULL,
    PARKING_ID       NUMBER,
    LAST_MESSAGE_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_conv_driver  FOREIGN KEY (DRIVER_ID)  REFERENCES APP_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT fk_conv_owner   FOREIGN KEY (OWNER_ID)   REFERENCES APP_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT fk_conv_parking FOREIGN KEY (PARKING_ID) REFERENCES PARKINGS(ID) ON DELETE SET NULL
);

CREATE INDEX idx_conv_driver ON CONVERSATIONS(DRIVER_ID);
CREATE INDEX idx_conv_owner  ON CONVERSATIONS(OWNER_ID);

-- Tabla de mensajes del chat
CREATE TABLE MESSAGES (
    ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONVERSATION_ID  NUMBER NOT NULL,
    SENDER_ID        NUMBER NOT NULL,
    CONTENT          VARCHAR2(2000) NOT NULL,
    IS_READ          NUMBER(1) DEFAULT 0,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_msg_conv   FOREIGN KEY (CONVERSATION_ID) REFERENCES CONVERSATIONS(ID) ON DELETE CASCADE,
    CONSTRAINT fk_msg_sender FOREIGN KEY (SENDER_ID)       REFERENCES APP_USERS(ID) ON DELETE CASCADE
);

CREATE INDEX idx_messages_conv   ON MESSAGES(CONVERSATION_ID);
CREATE INDEX idx_messages_sender ON MESSAGES(SENDER_ID);
