-- =========================================================
-- MiEstacionamiento - Features para propietarios
-- Ejecutar DESPUES de 01_create_tables.sql
-- Requiere permisos de ADMIN en Oracle ADB
-- =========================================================

-- Agregar campo IS_ACTIVE a PARKINGS (1=activo visible, 0=congelado/oculto)
ALTER TABLE PARKINGS ADD IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL;

-- Tabla de reservas/arriendos realizados por conductores
CREATE TABLE BOOKINGS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PARKING_ID  NUMBER NOT NULL REFERENCES PARKINGS(ID) ON DELETE CASCADE,
    DRIVER_ID   NUMBER NOT NULL REFERENCES APP_USERS(ID) ON DELETE CASCADE,
    HOURS       NUMBER(5,2) DEFAULT 1,
    AMOUNT      NUMBER(10,2) DEFAULT 0,
    STATUS      VARCHAR2(20) DEFAULT 'COMPLETED'
                CHECK (STATUS IN ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED')),
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_BOOKINGS_PARKING ON BOOKINGS(PARKING_ID);
CREATE INDEX IDX_BOOKINGS_DRIVER  ON BOOKINGS(DRIVER_ID);
CREATE INDEX IDX_BOOKINGS_DATE    ON BOOKINGS(CREATED_AT DESC);
CREATE INDEX IDX_PARKINGS_ACTIVE  ON PARKINGS(IS_ACTIVE);

COMMIT;
